//%attributes = {"invisible":true}
C_LONGINT:C283($1; $keyType)

$keyType:=$1

Case of 
	: ($keyType=KEYTYPE_PLAY)
		Form:C1466.KEY:="PLAY"
	: ($keyType=KEYTYPE_BRIGHTNESS_DOWN)
		Form:C1466.KEY:="BRIGHTNESS_DOWN"
	: ($keyType=KEYTYPE_BRIGHTNESS_UP)
		Form:C1466.KEY:="BRIGHTNESS_UP"
	: ($keyType=KEYTYPE_CAPS_LOCK)
		Form:C1466.KEY:="CAPS_LOCK"
	: ($keyType=KEYTYPE_CONTRAST_DOWN)
		Form:C1466.KEY:="CONTRAST_DOWN"
	: ($keyType=KEYTYPE_CONTRAST_UP)
		Form:C1466.KEY:="CONTRAST_UP"
	: ($keyType=KEYTYPE_DOWN_ARROW_KEY)
		Form:C1466.KEY:="DOWN_ARROW_KEY"
	: ($keyType=KEYTYPE_EJECT)
		Form:C1466.KEY:="EJECT"
	: ($keyType=KEYTYPE_FAST)
		Form:C1466.KEY:="FAST"
	: ($keyType=KEYTYPE_HELP)
		Form:C1466.KEY:="HELP"
	: ($keyType=KEYTYPE_ILLUMINATION_DOWN)
		Form:C1466.KEY:="ILLUMINATION_DOWN"
	: ($keyType=KEYTYPE_ILLUMINATION_TOGGLE)
		Form:C1466.KEY:="ILLUMINATION_TOGGLE"
	: ($keyType=KEYTYPE_ILLUMINATION_UP)
		Form:C1466.KEY:="ILLUMINATION_UP"
	: ($keyType=KEYTYPE_LAUNCH_PANEL)
		Form:C1466.KEY:="LAUNCH_PANEL"
	: ($keyType=KEYTYPE_MUTE)
		Form:C1466.KEY:="MUTE"
	: ($keyType=KEYTYPE_NEXT)
		Form:C1466.KEY:="NEXT"
	: ($keyType=KEYTYPE_NUM_LOCK)
		Form:C1466.KEY:="NUM_LOCK"
	: ($keyType=KEYTYPE_PLAY)
		Form:C1466.KEY:="PLAY"
	: ($keyType=KEYTYPE_POWER_KEY)
		Form:C1466.KEY:="POWER_KEY"
	: ($keyType=KEYTYPE_PREVIOUS)
		Form:C1466.KEY:="PREVIOUS"
	: ($keyType=KEYTYPE_REWIND)
		Form:C1466.KEY:="REWIND"
	: ($keyType=KEYTYPE_SOUND_DOWN)
		Form:C1466.KEY:="SOUND_DOWN"
	: ($keyType=KEYTYPE_SOUND_UP)
		Form:C1466.KEY:="SOUND_UP"
	: ($keyType=KEYTYPE_UP_ARROW_KEY)
		Form:C1466.KEY:="UP_ARROW_KEY"
	: ($keyType=KEYTYPE_VIDMIRROR)
		Form:C1466.KEY:="VIDMIRROR"
	Else 
		Form:C1466.KEY:=String:C10($keyType)
End case 
